project:
  type: website

website:
  title: "Hitesh Kishore Das"

  open-graph: true

  reader-mode: true

  page-footer:
    left: "This work is licensed under [CC BY NC ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/)"
    right: "Created using [Quarto](https://quarto.org/)"

  page-navigation: true

  search:
    location: navbar
    type: textbox

  sidebar:
    style: "docked"
    search: true
    pinned: true
    collapse-level: 1
    tools:
      - icon: twitter
        href: https://twitter.com/hitesh_k_das
      - icon: github
        href: https://github.com/hiteshkishoredas
    contents: 
      - text: About
        href: about.qmd
      - section: Research
        contents: research/*
      - text: Other stuff
        href: other_stuff.qmd
      # - section: Other Stuff
      #   contents: other_stuff/*
      # - section: Blogs
      #   contents: blogs/*

  navbar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/HiteshKishoreDas/hiteshkishoredas.github.io
          - text: Report a Bug
            url:  https://github.com/HiteshKishoreDas/hiteshkishoredas.github.io/issues
    left:
      - href: index.qmd
        text: Home

      - href: research.qmd
        text: Research
        
      - href: other_stuff.qmd
        text: Other Stuff

      # - href: blog_list.qmd
      #   text: Blogs

      - href: about.qmd
        text: About


format:
  html:
    # theme: cosmo
    # theme: flatly
    # theme: darkly
    # theme: solar
    # theme: lux
    # theme: minty
    theme:
      dark: [scss/theme-dark.scss, lux]
      light: [scss/theme-light.scss, lux]
    smooth-scroll: true
    fontsize: 2.0vh
    page-layout: full
    max-width: 100%
    css: styles.css
    toc: true
    grid:
      sidebar-width: 400px
      body-width: 1000px
execute:
  freeze: auto