---
title: "Magnetic Fields in Multiphase Turbulence"
# sidebar: false
---

Hi there!

In this page we show some interesting visualisations from our paper "Magnetic Fields in Multiphase Turbulence: 
Impacts on Dynamics and Structure" ([2307.06411](https://arxiv.org/abs/2307.06411)).

You can also find a monthly highlight article on MPA website [here](https://www.mpa-garching.mpg.de/1087631/hl202311?c=1096623), about this research.

The components, namely, Turbulence, Multiphase gas and Magnetic fields 
are ubiquitous in astrophysical media. But, there has been only limited work on the intersection of all
three parts. This work was an attempt to broaden the understanding at this intersection.
In particular, to look at how magnetic fields affect the growth and survival of multiphase gas in a turbulent medium.   

For this study, we use two sets of simulations: Turbulent Radiative Mixing Layers (TRMLs) and turbulent boxes.

Below we show the different visualisations from these two simulations.

## Turbulent Radiative Mixing Layers (TRMLs)

Here's a evolution in temperature showing a sliced view of different TRML simulations, along with the magnetic field lines:
{{< video https://www.youtube.com/embed/xDP1CS5wlLM >}}

It shows how the two phases are getting mixed and how the magnetic field topology evolves with time. 

And here's a evolution in scalar quantity showing a sliced view of different TRML simulations, along with the magnetic field lines.
This gives some hints towards the origin of gases in the different phases.
{{< video https://www.youtube.com/embed/QuhMbvPJ6Bg >}}

## (Magneto-)Hydrodynamic turbulent boxes

Here are 3-dimensional views of the evolution of the cold gas after the introduction of a cold gas cloud in driven-turbulence.

Without magnetic fields:
{{< video https://www.youtube.com/embed/0fWcMqdDn3E >}}

With magnetic fields:
{{< video https://www.youtube.com/embed/IaylcB8tKxM >}}

These clearly show the morphological difference between the cold phase in Hydrodynamic and Magnetohydrodynamic turbulence.
The cold gas phase is much more filamentary in presence of magnetic fields.

For a more stable view, here's a similar set of videos but as density projection.

* This is for a case where the cloud get's destroyed
{{< video https://www.youtube.com/embed/KJKwZ34hTuw >}}
 
* The cases where the cloud survives and cold gas grows
{{< video https://www.youtube.com/embed/A7nkFZaVaGg >}}


