---
title: "" 
sidebar: false

format:
    html:
        toc: true
        toc-depth: 2
        toc-location: left
        html-math-method: katex
    pdf:
        author: Hitesh Kishore Das
        pdf-engine: weasyprint
css: cv.css
format-links: [pdf]
---

<!-- ::: {.content-visible when-format="html"} -->
::: {.no-print}
Link to the PDF version of my [CV](cv_new.pdf), [short version](cv_short.pdf) 

:::

# Hitesh Kishore Das


:::: {.columns}

::: {.column width="40%"}
Max-Planck-Institut für Astrophysik   
Karl-Schwarzschild-Str. 1     
85748 Garching, Germany
:::

::: {.column width="60%"}
[hitesh[AT]mpa-garching.mpg.de](mailto:hitesh@mpa-garching.mpg.de)    
[hiteshkishored[AT]gmail.com](mailto:hiteshkishored@gmail.com)    
Website: [hiteshkishoredas.github.io](https://hiteshkishoredas.github.io)   
Skype  : hiteshkishoredas     
Phone  : +49 89 30000 - (2239) (MPA)   
:::

::::


__________________________________________________________


## Education       
__________________________________________________________

 
**PhD in Astrophysics (Ongoing)**   
Thesis title: The dynamics of multiphase gas in astrophysical media     

International Max Planck Research School on Astrophysics (IMPRS)     
Max Planck Institute for Astrophysics (MPA), Garching, Germany     
Ludwig Maximilians University (LMU), Munich, Germany    

Duration: Aug 2021-Present    
Doctoral Advisor: Dr. Max Gronke     
Formal supervisor: Prof. Volker Springel     

**Master of Science**    
Indian Institute of Science (IISc), Bengaluru, India   
Major: Physics    
Duration: Aug 2020 - July 2021    

**Bachelor of Science (Research)**     
Indian Institute of Science (IISc), Bengaluru, India  
Major: Physics   
Duration: Aug 2016 - July 2020    

<!-- **Senior Secondary (CBSE), 2016**
Kendriya Vidyalaya No-4, Bhubaneswar, India    
Stream: Science    
Date: 21/05/2016    -->


## Research Experience      
__________________________________________________________

- **Subgrid model for multiphase gas interactions** [ FEB 2024 - ]      
<!-- We are developing a subgrid model for survival, destruction and other behaviours of multiphase gas, using the Multifluid AREPO framework.     
The project is part of my PhD thesis, supervised by Dr. Max Gronke.  -->
Collaborators: Rainer Weinberger, Dr. Max Gronke    
<!-- Max Planck Institute for Astrophysics, Garching  -->


- **Three-phase gas in a turbulent medium**  [ MAY 2024 - ]      
Project is led by Zewei "Jason" Wu from UChicago during his DAAD-RISE internship. Involved as the advisor for his internship, including framing the research proposal.    
<!-- In this project we are investigating the cold molecular gas in a turbulent medium, where both "warm" and "hot" gas phases are also possible.   
-->
Collaborators: Zewei "Jason" Wu, Dr. Max Gronke       
<!-- Max Planck Institute for Astrophysics, Garching      -->


- **Linear and nonlinear evolution of thermal instability in 2D/3D**  [ MAR 2021 - ]        
<!-- In this project we extend our previous work on thermal instability to 2D and 3D systems. We investigate both linear and non-linear evolution of multiphase gas due to radiative cooling.     
This project contributed towards my Masters thesis, supervised by Prof. Prateek Sharma.     -->
Collaborator: Dr. Prakriti Pal Choudhury, Prof. Prateek Sharma      
<!-- Physical Sciences, Indian Institute of Science, Bangalore       -->


- **Survival, destruction and formation of cold molecular gas**  [ MAY 2023 - AUG 2023 ]       
<!-- In this project we are investigating the in-situ formation of cold molecular gas from "warm" gas and its subsequent survival or destruction, in presence turbulence.  -->
Part of the work was done by Atal Agarwal from IIT Roorkee during his DAAD-WISE internship. I was involved in the intership as a co-supervisor.     
<!-- The project is also part of my PhD thesis, supervised by Dr. Max Gronke.-->
Collaborators: Atal Agarwal, Dr. Max Gronke     
<!-- Max Planck Institute for Astrophysics, Garching      -->


- **Multiphase gas dynamics in Magnetised, turbulent medium**  [ SEP 2021 - JAN 2024 ]     
<!-- We studied the different aspects of multiphase gas, like survival, morphology and growth, in  a turbulent medium in presence of magnetic fields. We use idealised MHD simulations run using Athena ++ for this study.     
This led to a publication on MNRAS Jan 2024 issue. The project is part of my thesis project, supervised by Dr. Max Gronke.    -->
Collaborators: Dr. Max Gronke     
<!-- Max Planck Institute for Astrophysics, Garching       -->


- **Role of temperature and metallicity in the evolution of thermal instability** [ AUG 2019 - APR 2021 ]     
<!-- In this project we investigate the role of different parameters like metallicity and temperature in the growth of thermal instability. The project includes setting up and running simulation for study of thermal instabilities using PLUTO.   
This work led to some important insights into evolution of large-scale isochoric clouds.    

This project contributed towards my Bachelors thesis, supervised by Prof. Prateek Sharma and led to a research paper in collaboration with Dr. Prakriti Pal Choudhury and Prof. Prateek Sharma.-->
Part of Bachelors thesis project under the supervision of Prof. Prateek Sharma
Collaborators: Dr. Prakriti Pal Choudhury, Prof. Prateek Sharma     
<!-- Physical Sciences, Indian Institute of Science, Bangalore       -->
       

- *Computational Studies of Systems of Self-driven Particles [ 8 MAY 2019 – 12 JUL 2019 ]    
<!-- This project aimed at investigating the underlying physical origin of this "phase transition" via the development of appropriate computational models. The project goals included:     
- Molecular dynamics code development (in LAMMPS), adapting existing code in the research group    
- Reproduction of literature data   
-->
Internship under supervision of: Assoc. Prof. Massimo Pica Ciamarra (NTU, Singapore)    


<!-- - *Electrostatics of Spherical Topological Insulators [ 1 MAY 2018 – 30 JUN 2018 ]   
 Theoretical derivation of electric and magnetic scalar potentials for different cases of electric and magnetic fields near a spherical Topological insulator.    

Under supervision of: Assoc. Prof. Subroto Mukerjee    
Physical Sciences, Indian Institute of Science, Bangalore    -->


<!-- - *Analysis of data from CERN 2010 open data and simulation of top pair production [ 1 MAY 2017 – 31 JUL 2017 ]   
It consisted of accessing CERN 2010 open data using CernVM and analysing the data using C++ and Python code incorporating ROOT to plot Dimuon spectra, Trimuon spectra and other related plots.   
High-energy particle physics event simulations of top pair production were done using Pythia 8.2 and Madgraph 5.    

Under supervision of: Asst. Prof. Jyothsna Rani Komaragiri   
Centre for High Energy Physics, Indian Institute of Science, Bangalore     -->


<!-- #### Special Relativity and Elementary Particle Physics (Reading Project)
**[ 1 MAY 2017 – 31 JUL 2017 ]**    
Study of Special Relativity from "Special Relativity" by Robert Resnick and Elementary Particle Physics from "Introduction to Elementary Particles" by David Griffith.     

Under supervision of: Asst. Prof. Jyothsna Rani Komaragiri    
Centre for High Energy Physics, Indian Institute of Science, Bangalore     -->




## Publications      
__________________________________________________________

##### - Magnetic Fields in Multiphase Turbulence: Impacts on Dynamics and Structure
Hitesh Kishore Das, Max Gronke     
Monthly Notices of the Royal Astronomical Society, Volume 527, Issue 1, January 2024, Pages 991–1013, [doi.org/10.1093/mnras/stad3125](https://doi.org/10.1093/mnras/stad3125)  
**arXiv**: [2307.06411](https://arxiv.org/abs/2307.06411)

##### - Shatter or not: role of temperature and metallicity in the evolution of thermal instability
Hitesh Kishore Das, Prakriti Pal Choudhury, Prateek Sharma    
**Journal**: Monthly Notices of the Royal Astronomical Society, Volume 502, Issue 4, April 2021, Pages 4935–4952, [doi.org/10.1093/mnras/stab382](https://doi.org/10.1093/mnras/stab382)    
**arXiv**: [2009.11317](https://arxiv.org/abs/2009.11317) 


## Conferences and Seminars     
__________________________________________________________


- **Talk** at Lars Hernquist group meeting at **Center for Astrophyiscs**, Harvard University on August 23, 2024.

- **Multiphase Madness: Resolving the CGM in Theory and Observations** (August 21-23, 2024). 
Gave a **talk** in-person at Center for Astrophysics, Harvard University, Cambridge.

- **Talk** at Computational Structure and Galaxy formation group meeting at **MIT Kavli Institute for Astrophyiscs** on August 19, 2024.   

- **Talk** in GalRead at Peyton Hall, **Princeton University**, on August 16, 2024.   

- **Team meeting for "Observe Local Think Global: What Solar Observations can teach us about Multiphase Plasmas across Astrophysical Scales"**    
(May 13-17, 2024)   
**Presented** my work. In-person at ISSI, Bern, Switzerland   

- **Talk** in **Cosmology section meeting** at AIP, Potsdam, on May 8, 2024.     

- **Annual Astronomical Society of India (ASI) meeting** 2024 (Jan 30-Feb 4, 2024).    
Presented a \textbf{poster} at IISc, Bangalore, India.

- **2023 IAP colloquium: New simulations for new problems in galaxy formation** (December 11-15, 2023). 
Gave a \textbf{talk} in-person at IAP, Paris, France.

- **MIST2023 : Cosmic turbulence and Magnetic fields** (September 24 - October 1, 2023)
Gave a \textbf{talk} in-person at Cargese, Corsica, France.

- **Modelling of Multiphase Astrophysical Media** (May 30-June 2, 2023)   
Presented a ~15 min talk about my work. In-person at Aspenstein Castle, near Lake Kochel, Germany   

- **MPA weekly Institute Seminar** (May 15, 2023)    
Presented a ~45 min talk about my work. In-person at MPA, Garching, Germany    

- **52nd Saas-Fee winter School on "The Circum-Galactic Medium across cosmic time: an observational and modelling challenge"**   
(March 19-24, 2023)   
Presented a poster about my work. In-person at Les Diablerets, Switzerland   

- **Team meeting for "Observe Local Think Global: What Solar Observations can teach us about Multiphase Plasmas across Astrophysical Scales"**    
(March 13-17, 2023)   
Presented an introduction for simulations in ICM/CGM, and my work. In-person at ISSI, Bern, Switzerland   

- **The Multiphase Circumgalactic Medium** (February 26- March 3, 2023)    
Presented a ~15 min talk about my work. In-person at Ringberg Castle, Germany    
 
- **Lyman-X Day: ORIGINS workshop** (October 5, 2022)     
Attended in-person at European Southern Observatory (ESO), Garching     

- **The National Astronomy Meeting (NAM) 2022** (July 11-15, 2022)     
Attended virtually and submitted a poster for the parallel session "Non-equilibrium thermodynamics across scales: from the solar corona to the intracluster medium".   

- **Gas Flows around Galaxies: ORIGINS workshop** (May 24, 2022)    
Presented my work in-person at MPA, Garching     

- **Presision Presidency Physics Summit** (September 11-13, 2020)   
Organized by Presidency University, Kolkata    
Presented work done on Thermal Instability as a talk in the Undergraduate Symposium.

- **On the Origin, Nature, and Mixing of Multiphase Gas in Astrophysics** KITP online conference (October 15-16, 2020)     
Attended the conference virtually

- **IAP online Colloquium on Intracluster Medium/Circumgalactic medium** (June 22-26, 2020)     
Attended the conference virtually    

## Mentoring      
__________________________________________________________


- Fully **Supervised** the DAAD-RISE intership of Zewei "Jason" Wu (UChicago) at MPA, Garching between May - August 2024

- **Co-supervised** the DAAD-WISE intership of Atal Agarwal (IIT Roorkee) at MPA, Garching between May-August 2023

- **Mentored** Tapan Mayukh from LMU during their Masters thesis project at MPA during 2023-24 academic year


## Service      
__________________________________________________________

- Refereed:
    - Scientific article for A&A
    - Computating time proposal for DIRAC HPC facility

- **External PhD representative** at MPA (July 2024-)

- **13th IMPRS Symposium**: Chair of the Local Organising Committee

## Extra-curricular Experience      
__________________________________________________________

- **IISc Undergraduate Astro Club**    
Delivered a talk on "Astrophysical media and their behaviour". 

- **IISc Undergraduate Physics Club**    
Delivered a talk on "Special Relativity and Minkowski Diagrams".    

- **Indian Instiute of Science Open Day**    
Constructed and demonstrated an experiment about Bernard convection cells on Sun.

- **Institute Fest - "Pravega"**     
Involved in planning and conducting events by Physics club for Pravega - 2016 and Pravega - 2017.     
<!-- Event coordinator for the "Vacuum cannon" event in Pravega-2017 -->
     

## Awards and Fellowships         
__________________________________________________________

- Funded **Max Planck Society PhD position**      
Funding for the PhD salary at MPA
Duration: Sept 2021 - Sept 2025

- **NTU-India Connect Research Fellowship** 
2-month long intership opportunity at NTU, with funding for travel, accommodation and living costs.
Funded by: Nanyang Technological University, Singapore (NTU)
Duration: May 2019 – July 2019   

- **Kishore Vaigyanik Protsahan Yojana** (KVPY) Fellowship}    
Funded by: Department of Science and Technology, Government of India    
Stream: SX     
Duration: 2016-2021     

<!-- - **National Cyber Olympiad** 2014-15   
National Rank: 1 (in 11th grade)     
Organised by: Science Olympiad Foundation    

- **National Standard Examination in Astronomy** , 2015    
Got certificate for being in top 10\% of the examination centre.    
Organised by: Indian Association of Physics Teachers (IAPT)     -->


## Skills     

::: {.no-print}

:::: {.columns}
::: {.column width="35%"}
C, C++    
Athena++    
LAMMPS   
Madgraph 5    
Mathematica    
High Performance Computing     
LaTeX
:::
::: {.column width="50%"}
Python    
PLUTO    
ROOT   
Pythia 8.2    
SQL   
Matlab    
Bash scripting    
:::
::::
:::

::: {.print-only}
**Compiled languages**: C, C++    
**Hydrodynamic Simulation**: AREPO, Athena++ , PLUTO      
**Interpreted languages**: Python, Matlab, Mathematica    
**Others**: LaTeX, ROOT, Bash scripting, High Performance Computing, LAMMPS, Madgraph 5, Pythia          
:::

<!-- ## Standardised Tests 

+-----------------+---------------+---------------------------+
| **GRE General** | - Total : 330 | - Quantitative: 169       |
|                 |               | - Verbal      : 161       |
|                 |               | - Analytical Writing: 4.0 |
+-----------------+---------------+---------------------------+
| **TOEFL-iBT**   | Total : 108   | - Reading   : 29          |
|                 |               | - Listerning: 30          |
|                 |               | - Speaking  : 24          |
|                 |               | - Writing   : 25          |
+-----------------+---------------+---------------------------+
| **GRE Physics** | Score: 89%ile |                           |
|                 |               |                           |
+-----------------+---------------+---------------------------+ -->



## Language proficiency

- English (Proficient)
- Hindi (Proficient)
- Odia (Native)
- German (Beginner A1)

{{< pagebreak >}}

## Worked with

#### Dr. Max Gronke
Max Planck Institute for Astrophysics, Garching, Germany    
Email: maxbg[AT]mpa-garching.mpg.de    
Website: [max.lyman-alpha.com](http://max.lyman-alpha.com)   

#### Prof. Prateek Sharma
Physical Sciences   
Indian Institute of Science, Bangalore, India   
Email: prateek[AT]iisc.ac.in    
Website: [www.physics.iisc.ernet.in/~prateek](http://www.physics.iisc.ernet.in/~prateek/)     

#### Dr. Rainer Weinberger   
Leibniz Instiute for Astrophyiscs (AIP), Potsdam, Germany     
Email: rweinberger[AT]aip.de    
Website: [rainerweinberger.com](https://rainerweinberger.com/)     

#### Assoc. Prof. Massimo Pica Ciamarra
Nanyang Associate Professor    
School of Physical & Mathematical Sciences    
Nanyang Technological University, Singapore    
Email: massimo[AT]ntu.edu.sg    
Website: [sites.google.com/site/ciamarragroup](https://sites.google.com/site/ciamarragroup/)     

<!-- #### Assoc. Prof. Subroto Mukerjee
Physical Sciences      
Indian Institute of Science, Bangalore, India    
Email: smukerjee[AT]iisc.ac.in    
Website: [physics.iisc.ernet.in/~smukerjee](http://physics.iisc.ernet.in/~smukerjee)   
 
#### Asst. Prof. Jyothsna Rani Komaragiri
Centre for High Energy Physics    
Indian Institute of Science, Bangalore, India  
Email: jyothsna.komaragiri[AT]gmail.com    
Website: [chep.iisc.ac.in/Personnel/pages/jyothsna](http://chep.iisc.ac.in/Personnel/pages/jyothsna)      -->