---
title: "" 
sidebar: false

format:
    html:
        toc: true
        toc-depth: 2
        toc-location: left
        html-math-method: katex
    pdf:
        documentclass: article #[a4paper,11pt,oneside]{article}
        classoption: [a4paper,11pt,oneside]
        geometry:
            - left=20mm 
            - right=20mm 
            - bottom=20mm 
            - top=20mm
        keep-tex: true

# \usepackage{url}
# %\usepackage[utf8]{inputenc}
# %\usepackage{setspace}
# \usepackage{hyperref}
# \usepackage{graphicx}
# \usepackage[left=0.75in, right=1in, bottom=0.75in, top=0.5in]{geometry}

# \newcommand*{\Skype}{\href{skype:hiteshkishoredas?add}{hiteshkishoredas}} 
# \newcommand{\Absender}[1][\normalsize]{\Skype} 
---

::: {.content-visible when-format="html"}

Link to the PDF version of my [CV](cv.pdf), [short version](cv_short.pdf) 

:::

# Hitesh Kishore Das

::: {.content-visible when-format="html"}
__________________________________________________________
:::
::: {.content-visible when-format="pdf"}
\hrule
:::

:::: {.columns}

::: {.column width="40%"}
Max-Planck-Institut für Astrophysik   
Karl-Schwarzschild-Str. 1     
85748 Garching, Germany
:::

::: {.column width="60%"}
[hitesh[AT]mpa-garching.mpg.de](mailto:hitesh@mpa-garching.mpg.de)    
[hiteshkishored[AT]gmail.com](mailto:hiteshkishored@gmail.com)    
Website: [hiteshkishoredas.github.io](https://hiteshkishoredas.github.io)   
Skype  : hiteshkishoredas     
Phone  : +49 89 30000 - (2239) (MPA)   
:::

::::

::: {.content-visible when-format="html"}
__________________________________________________________
:::
::: {.content-visible when-format="pdf"}
\hrule
:::

## Education

 
**PhD in Astrophysics} (Ongoing)**   
International Max Planck Research School on Astrophysics (IMPRS)   
Max Planck Institute for Astrophysics (MPA), Garching, Germany    
Ludwig Maximilians University (LMU), Munich, Germany  
Duration: 2021-Present     

**Master of Science}**    
Indian Institute of Science (IISc), Bengaluru, India   
Major: Physics    
Duration: 2020-2021   

**Bachelor of Science (Research)}** 
Indian Institute of Science (IISc), Bengaluru, India  
Major: Physics   
Duration: 2016-2020   

## Research Experience

#### The dynamics of magnetized, multiphase gas in a turbulent environment   
**[ 8 SEP 2021 - PRESENT ]**  
We are studying the different aspects of multiphase gas, like survival, morphology and growth, in  a turbulent medium in presence of magnetic fields. We use idealised MHD simulations run using Athena ++ for this study.   

Doctoral Advisor: Dr. Max Gronke     
Formal supervisor: Prof. Volker Springel    
Max Planck Institute for Astrophysics, Garching   


#### Role of temperature and metallicity in the evolution of thermal instability    
**[ 1 AUG 2019 - PRESENT ]**     
This project contributed towards my Bachelors thesis and led to a research paper in collaboration with Dr. Prakriti Pal Choudhury and Prof. Prateek Sharma.   

Under supervision of: Assoc. Prof. Prateek Sharma    
Collaborator: Dr. Prakriti Pal Choudhury
Physical Sciences, Indian Institute of Science, Bangalore   
       

#### Computational Studies of Systems of Self-driven Particles       
**[ 8 MAY 2019 – 12 JUL 2019 ]**    
This project aimed at investigating the underlying physical origin of this "phase transition" via the development of appropriate computational models. 

Under supervision of: Assoc. Prof. Massimo Pica Ciamarra    
School of Physical \& Mathematical Sciences, Nanyang Technological University, Singapore     -->


## Publications


##### - Magnetic Fields in Multiphase Turbulence: Impacts on Dynamics and Structure
Hitesh Kishore Das, Max Gronke   
**arXiv**: [2307.06411](https://arxiv.org/abs/2307.06411) 

##### - Shatter or not: role of temperature and metallicity in the evolution of thermal instability
Hitesh Kishore Das, Prakriti Pal Choudhury, Prateek Sharma   
**Journal**: Monthly Notices of the Royal Astronomical Society, Volume 502, Issue 4, April 2021, Pages 4935–4952, [doi.org/10.1093/mnras/stab382](https://doi.org/10.1093/mnras/stab382)    
**arXiv**: [2009.11317](https://arxiv.org/abs/2009.11317) 


## Conferences and Seminars

- **Modelling of Multiphase Astrophysical Media** (May 30-June 2, 2023)   
Presented a ~15 min talk about my work. In-person at Aspenstein Castle, near Lake Kochel, Germany   

- **MPA weekly Institute Seminar** (May 15, 2023)    
Presented a ~45 min talk about my work. In-person at MPA, Garching, Germany    

- **52nd Saas-Fee winter School on "The Circum-Galactic Medium across cosmic time: an observational and modelling challenge"**   
(March 19-24, 2023)   
Presented a poster about my work. In-person at Les Diablerets, Switzerland   

- **Team meeting for "Observe Local Think Global: What Solar Observations can teach us about Multiphase Plasmas across Astrophysical Scales"**    
(March 13-17, 2023)   
Presented an introduction for simulations in ICM/CGM, and my work. In-person at ISSI, Bern, Switzerland   

- **The Multiphase Circumgalactic Medium** (February 26- March 3, 2023)    
Presented a ~15 min talk about my work. In-person at Ringberg Castle, Germany    
 
- **Lyman-X Day: ORIGINS workshop** (October 5, 2022)     
Attended in-person at European Southern Observatory (ESO), Garching     

- **The National Astronomy Meeting (NAM) 2022** (July 11-15, 2022)     
Attended virtually and submitted a poster for the parallel session "Non-equilibrium thermodynamics across scales: from the solar corona to the intracluster medium".   

- **Gas Flows around Galaxies: ORIGINS workshop** (May 24, 2022)    
Presented my work in-person at MPA, Garching     


{{< pagebreak >}}